baseurl: /thoroughbass-chorales
title: Thoroughbass Chorales
author: Victor Phan
simple_search: http://google.com/search
description: thoroughbass chorales description
name: thoroughbass-chorales
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md']
page:
  template: _page.txt
  extension: md
destination: docs/