baseurl: /figured-chorales
title: Figured Chorales
author: Victor Phan
simple_search: http://google.com/search
description: figured chorales description
name: figuredchorales
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md']
page:
  template: _page.txt
  extension: md